spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/board-db
    username: board-master
    password: board-postgres-password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: board-admin
      password: board-admin-password
logging:
  # trace < debug < info < warn < error
  level:
    root: INFO


